blank_issues_enabled: false
contact_links:
  - about: |
      This issue tracker is specifically for the website on learningtypescript.com.
      It pulls project content from github.com/LearningTypeScript/projects.
      Go here to report an issue with a project.
    name: Looking for the Projects Issue Tracker?
    url: https://github.com/JoshuaKGoldberg/learning-typescript
  - name: Help with TypeScript concepts
    about: The TypeScript Discord is a great place for asking for help on your TypeScript journey!
    url: https://discord.com/invite/typescript
  - name: Contact Josh
    about: Want to ask for help more individually? DM or post on Bluesky.
    url: https://bsky.app/profile/learningtypescript.com
